### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by auxfuse** [auxfuse/how-patrick-are-you#1]
To create basic wireframes to suit the project.

Include layout per component and page.

**Comment by maelou363** [comment]
![Desktop Quiz Final Question Copy](https://user-images.githubusercontent.com/75320994/110210137-354fb400-7e88-11eb-908e-38960205abd7.png)
![Desktop Quiz Final Question](https://user-images.githubusercontent.com/75320994/110210138-384aa480-7e88-11eb-9969-ad23acbc58dc.png)
![Desktop Quiz](https://user-images.githubusercontent.com/75320994/110210139-38e33b00-7e88-11eb-8e55-d029ad6011fd.png)
![Desktop](https://user-images.githubusercontent.com/75320994/110210140-397bd180-7e88-11eb-86e3-46ad83b20528.png)
![Mobile Landing](https://user-images.githubusercontent.com/75320994/110210141-3a146800-7e88-11eb-8806-9fb3f4e8c879.png)
![Mobile 2](https://user-images.githubusercontent.com/75320994/110210142-3aacfe80-7e88-11eb-9814-37490d062131.png)
![Mobile Quiz Submit](https://user-images.githubusercontent.com/75320994/110210144-3b459500-7e88-11eb-88cb-469c412e4360.png)
![Mobile Quiz](https://user-images.githubusercontent.com/75320994/110210145-3b459500-7e88-11eb-9d30-41bae4e224cf.png)
![Mobile Results 30%](https://user-images.githubusercontent.com/75320994/110210147-3bde2b80-7e88-11eb-898f-960f96c12fa0.png)
![Mobile Results 60%](https://user-images.githubusercontent.com/75320994/110210148-3c76c200-7e88-11eb-9d10-9cdcf3af3023.png)
![Mobile Results  Over 80%](https://user-images.githubusercontent.com/75320994/110210149-3c76c200-7e88-11eb-9204-404e00eded1b.png)
![505 Desktop](https://user-images.githubusercontent.com/75320994/110210151-3ed91c00-7e88-11eb-9b0d-545c41fa3e4d.png)
![505](https://user-images.githubusercontent.com/75320994/110210153-41d40c80-7e88-11eb-83e1-d1eb5da427f2.png)

**Comment by auxfuse** [comment]
Wireframes created as seen above in comments from @maelou363 

Closing issue to suit creation
