### ISSUE TITLE
Results screen....modal

### ISSUE THREAD

**Issue by auxfuse** [auxfuse/how-patrick-are-you#11]
to include:
* prize(s)
* buttons for reset/cancel/leaderboard
* background click disabled...
* store results in local storage
* Link back into quiz.js containers etc, so results can be displayed

**Comment by kgwilde** [comment]
Modal Card - https://bulma.io/documentation/components/modal/#modal-card

Contents:
* Congratulatory Message
* Score (%)
* Semantic Image (Good, Bad, Almost) 
* Buttons:
  1. Exit
  2. View Leaderboard
  3. Try Again
* Use Local Storage to store '% Score' and if the User has played the game yet 'True/False'
 
```
user {
   score: <integer>,
   gamePlayed: <boolean>
}
```

**Comment by auxfuse** [comment]
Component created and merged #30
