### ISSUE TITLE
Create Leaderboard page

### ISSUE THREAD

**Issue by auxfuse** [auxfuse/how-patrick-are-you#18]
To include scores collated from Firebase? 

Filter by largest to smallert, and to include tie-breaker functionality.

**Comment by kgwilde** [comment]
When a User completes the Quiz, create a POST to Firebase, storing `name`, `score` and `timestamp`.

To display Leaderboard, get all documents from the collection.  Sort by score. *Figure out a way to solve for tie-breakers, use timestamp?

**Comment by kgwilde** [comment]
initial Leaderboard page created + leaderboard.js to get / post data to Firebase #34

**Comment by auxfuse** [comment]
Closing to suit merge #34
