### ISSUE TITLE
Frontend Framework use?

### ISSUE THREAD

**Issue by kenwilde1** [auxfuse/how-patrick-are-you#20]
* Bootstrap 5
* UIKit
* Tailwind
* Bulma

**Comment by kgwilde** [comment]
## Bootstrap 5

* Good for responsive layout design across devices using the Grid System. 
* Comes with a lot of built-in components such as Modals, Spinners, Hamburger Menus etc
* Most members in the team will be more familiar with Bootstrap than any other framework / library. 
* Bootstrap 5 no longer has jQuery so no bloated libraries

## UIKit

* Lightweight - load times? 
* Also has it's Grid System for responsive layouts
* Tons of components that are similar to Bootstrap. 
* Offers different designs to Bootstrap - most projects in the hackathon may use Bootstrap and therefore may all look similar. 

## Tailwind

* More Heavyweight than others - more assets to load but access to more components and utilities
* No default theme with Tailwind therefore better customisation allowed 
* Most people probably not experienced in Tailwind but that offers a chance to learn a new, cutting-edge tech

## Bulma

* Advertised as "easier" than other frameworks. 
* Self-resizing grid-system = less work to make responsive
* No JS
* Syntax is a lot more human readable compared to others.
  E.g To create a column you simply use the `.column` class whereas in Bootstrap you're defining `col-` and then a size.

**Comment by kgwilde** [comment]
Framework chosen: Bulma
https://bulma.io/documentation/
